[package]
name = "tcpbasics"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["serialize", "deserialize"] }
tokio = { version = "1", features = ["full"] }
bincode = "1.3"